version: "3.8"

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_recruit_web
    ports:
      - "8080:8000"
    environment:
      APP_ENV: local
      APP_KEY: base64:LKLw9ZXy+mqdrtS8hKPLbci1uSPIByIE97PQemLyJDw=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_DATABASE: smart_recruit
      DB_USERNAME: smart_recruit
      DB_PASSWORD: secret
      AI_SERVICE_URL: http://ai-service:8010
      SESSION_DRIVER: file
      CACHE_STORE: file
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    depends_on:
      - mysql-db
      - ai-service
    networks:
      - smart-recruit

  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: smart_recruit_ai
    ports:
      - "8010:8010"
    volumes:
      - ./ai-service:/app
    networks:
      - smart-recruit

  mysql-db:
    image: mysql:8.0
    container_name: smart_recruit_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: smart_recruit
      MYSQL_USER: smart_recruit
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - smart-recruit-mysql:/var/lib/mysql
    networks:
      - smart-recruit

networks:
  smart-recruit:
    driver: bridge

volumes:
  smart-recruit-mysql:
